// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uploader.Services;

namespace Uploader.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190928183003_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Uploader.Model.Investment", b =>
                {
                    b.Property<Guid>("InvestmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Collateral")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fund")
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvestmentId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("Uploader.Model.InvestmentTotal", b =>
                {
                    b.Property<Guid>("InvestmentTotalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CollateralTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValueTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvestmentTotalId");

                    b.ToTable("InvestmentTotals");
                });
#pragma warning restore 612, 618
        }
    }
}
